### ISSUE TITLE
Automate creation of meta data files

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/GENIE-Sponsored-Projects#31]
Currently, meta data files must be copied and modified manually to add to the generated cBioPortal files and for the cBioPortal validator to operate.

**Comment by thomasyu888** [comment]
Theres actually multiple ways to do this.  Theres the way I currently have it in the PR.  But also what I could have is something like this:

```
{
    "data_clinical_sample.txt": {
        "cancer_study_identifier": study_identifier,
        "genetic_alteration_type": alteration_type,
        "datatype": datatype
    }....
}
```

And a `write_yaml` function that takes `**kwargs`
```
def write_yaml(**kwargs):
    with open(meta_filename, "w") as meta_f:
        yaml.dump(kwargs, meta_f)
```

Then a parameter to pass in could be one cbioportal file or a list of cbioportal file names and the metadata files can be generated.

**Comment by hhunterzinck** [comment]
Since this cBioPortal file generation is specific to GENIE Sponsored projects and since the the metadata files are consistent across the cohorts, I think it's ok to have each file generated explicitly in main.  What I'd like to avoid is having to rely on the user to know and understand which cBioportal files need metadata files or, indeed, what these metadata files are.  Unless this could be automated based on a list of cBioportal files that exist after the program creates them?

**Comment by thomasyu888** [comment]
the metadata files are actually consistent across all of GENIE.  What we can do is create metadata files based on the existing cbioPortal files per cohort.  As you know, there are cohorts that don't actually create all the files - so if we created a metadata for it and uploaded it, it would fail cBioPortal import.

**Comment by hhunterzinck** [comment]
I see what you mean.  I think this goes back to tracking which files are created for which cohorts in the cohort classes. 
 Recording which files are created for which cohorts is necessary not only for metadata file generation but for the actual creating of the files themselves and avoiding any one-off checks by cohort.  

Could the class structure be modified to contain a list of cBioPortal files are relevant through some file identifier?  Then could the metadata file generation access these keys to determine which files to generate by cohort?

**Comment by thomasyu888** [comment]
Oh i see.  So an example configuration could be:

```
panc:
    cbioportalfiles: [timeline...., sample, patient...]
```

Although for most files, all file formats are created, and there are only SP that exclude certain file formats.

**Comment by hhunterzinck** [comment]
There are existing exceptions for BPC cohorts that do not collect relevant data.  For example: 
1. The TIMELINE-LAB file is not created for BLADDER and NSCLC
2. And the TIMELINE-TREATMENT file does not include TIMELINE-TREATMENT-RT for BrCa, CRC, NSCLC

**Comment by thomasyu888** [comment]
```
{"data_clinical_sample.txt": 
    {"alteration_type": "CLINICAL"
    "datatype": "SAMPLE_ATTRIBUTE"}
}.....

create_metadata_file(study_id, which_metadata_file_to_create, other_kwargs...)

create_meta_study_file()

if "data_clinical_sample.txt" in cbio_fileformats:
    create_meta_file(
        study_identifier=study_identifier,
        alteration_type="CLINICAL",
        datatype="SAMPLE_ATTRIBUTE",
        filename="data_clinical_sample.txt"
    )

    cbio_fileformats: list = [
        "data_clinical_sample.txt",
        "data_clinical_patient.txt",
        "data_clinical_supp_survival.txt",
        "data_clinical_supp_survival_treatment.txt",
        "data_gene_matrix.txt",
        "data_timeline_cancer_diagnosis.txt",
        "data_timeline_imaging.txt",
        "data_timeline_medonc.txt",
        "data_timeline_pathology.txt",
        "data_timeline_sample_acquisition.txt",
        "data_timeline_sequencing.txt",
        "data_timeline_treatment.txt",
        "data_timeline_labtest.txt",
        "data_CNA.txt",
        "data_fusions.txt",
        "data_mutations_extended.txt"
    ]

    for i in cbio_fileformats:
        figure out which function to call...
        store function to call vs key
```
