### ISSUE TITLE
Migrate Synapse table dependencies to yaml config files

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/GENIE-Sponsored-Projects#32]
Determine if and which Synapse table dependencies could be configured in a yaml file stored directly in the repo.  This change has the advantage of increasing consolidation and transparency of mappings and reducing reliance on Synapse.  Reducing reliance on Synapse could increase generalizability of the code base.

**Comment by thomasyu888** [comment]
After re-visiting this ticket, I realize I'm a little confused about this ticket.  Was the purpose to get rid of the synapse ids under each of the cohort Classes in `bpc_config.py`, or was it to find a synapse table that had mappings (similar to the main GENIE database to synapse id mapping table)?

**Comment by hhunterzinck** [comment]
@thomasyu888 I was thinking in particular of the `Data files for derived variables` table:

https://www.synapse.org/#!Synapse:syn22296821/tables/

and encoding the `id` to `dataset` name mapping directly in a yaml file for versioning with git and reducing the reliance on another reference external to the codebase.  

But if the file view provides a reference for cbio to remember which dataset names they need to include in the mapping file, maybe this isn't worth it.  I'm fine with closing this issue.
