### ISSUE TITLE
Fix missing start dates

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/GENIE-Sponsored-Projects#44]
Rows with missing start dates are still present in data_timeline_treatment.txt files

**Comment by thomasyu888** [comment]
We need a way to track the missing start dates if we remove them, because this is usually an error with the upstream data

**Comment by hhunterzinck** [comment]
Why does the following line not remove these rows?

https://github.com/Sage-Bionetworks/GENIE-Sponsored-Projects/blob/ea33ed8a587a3e8f53c4d504842606da83cb6f7b/geniesp/bpc_redcap_export_mapping.py#L590

**Comment by thomasyu888** [comment]
There are timeline files that are created by this function too: https://github.com/Sage-Bionetworks/GENIE-Sponsored-Projects/blob/ea33ed8a587a3e8f53c4d504842606da83cb6f7b/geniesp/bpc_redcap_export_mapping.py#L664

**Comment by hhunterzinck** [comment]
Would adding the equivalent filter on null values to the create_fixed_timeline_files function cause any issues?  

In terms of tracking, missing start dates for treatments are flagged by the stats team's complex queries and resolved by sites on subsequent data uploads.  Maybe we can just output warnings that we have removed them, but I don't think that we need track them closely.

**Comment by thomasyu888** [comment]
I'm honestly unsure of the impact, but we can always try it.
