### ISSUE TITLE
Organize Synapse entity specifications

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/GENIE-Sponsored-Projects#88]
1. Synapse entities that are constant across sponsored projects should be defined in the BPCRunner class, not the individual sponsored project classes
2. Consider Synapse table version specifications: specifying versions makes it necessary to update the code every time a mapping is updated and the mapping should be the most up to date anyway

**Comment by thomasyu888** [comment]
1. Agreed with this
2. The specific versions are required for provenance.  That said, what we could do is always take the latest version, and just get the version when setting provenance.

**Comment by hhunterzinck** [comment]
2.  Should be in provenance on Synapse to directly link the stored file to the table version.  I'll make another issue for this modification
